stages:
    - stage: build
    jobs:
    - job:
    pool:
    vmImange:''

- task: Docker@2
  inputs:
    containerRegistry: 'Docker-CGFootman'
    repository: 'cgfootman/heroes'
    command: 'build'
    Dockerfile: '**/ubuntu/Dockerfile'